// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yifeqanwapyqcgsnehoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpZmVxYW53YXB5cWNnc25laG9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxNTY5MDQsImV4cCI6MjA4ODczMjkwNH0.GgjuQD1JX4EA57VGjeIyljEGDSzxxDnVFWv3dQhB154";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});